spring:
  datasource:
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mariadb://localhost:3306/jaksho_new?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useInformationSchema=true
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 60
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000