POST {{endpoint}}/sr/api-definition

{
    "name": "createUser2",
    "bodyType": "RAW",
    "rawType": "JSON",
    "method": "POST",
    "path": "/user",
    "apiDefinitionFieldDTOList": [
        {
            "fieldType": "JSON",
            "bizFieldDomainId": 1,
            "sortOrder": 0
        }
    ],
    "description": "Test API definition"
}

###
POST {{endpoint}}/sr/api-definition

{
    "name": "createUser",
    "bodyType": "NONE",
    "method": "POST",
    "path": "/user3",
    "description": "Test API definition"
}

###
POST {{endpoint}}/sr/api-definition

{
    "name": "createUser3",
    "method": "POST",
    "path": "/user3",
    "description": "Test API definition"
}

###
POST {{endpoint}}/sr/api-definition

{
    "name": "createUser",
    "path": "/user",
    "description": "Test API definition",
    "bodyType": "NONE",
    "method": "POST"
}