POST {{endpoint}}/sr/api-definition

{
    "name": "createUser4",
    "bodyType": "RAW",
    "rawType": "JSON",
    "method": "POST",
    "path": "/user4",
    "apiDefinitionFieldDTOList": [
        {
            "fieldType": "JSON",
            "bizFieldDomainId": 1,
            "sortOrder": 0,
            "ulid": "1"
        },
        {
            "fieldType": "JSON",
            "bizFieldDomainId": 2,
            "sortOrder": 1,
            "ulid": "2"
        }
    ],
    "description": "Test API definition"
}

###
POST {{endpoint}}/sr/api-definition

{
    "name": "createUser",
    "bodyType": "NONE",
    "method": "POST",
    "path": "/user3",
    "description": "Test API definition"
}

###
POST {{endpoint}}/sr/api-definition

{
    "name": "createUser3",
    "method": "POST",
    "path": "/user3",
    "description": "Test API definition"
}

###
POST {{endpoint}}/sr/api-definition

{
    "name": "createUser",
    "path": "/user",
    "description": "Test API definition",
    "bodyType": "NONE",
    "method": "POST"
}