POST {{endpoint}}/sr/biz-field-type

{
    "name": "pass3",
    "collectionType" : "NONE",
    "basicFieldType": "object",
    "objectBizFieldTypeRefDTOList": [{
        "refId": 1,
        "parentId": 0,
        "sortOrder": 1
    }]
}