POST {{endpoint}}/sr/biz-field-type

{
    "name": "Password",
    "collectionType" : "NONE",
    "basicFieldType": "string",
    "minimum": 6,
    "maximum": 255
}

###
POST {{endpoint}}/sr/biz-field-type

{
    "name": "Str64",
    "collectionType" : "NONE",
    "basicFieldType": "string",
    "maximum": 64
}

###
POST {{endpoint}}/sr/biz-field-type

{
    "name": "Str128",
    "collectionType" : "NONE",
    "basicFieldType": "string",
    "maximum": 128
}

###
POST {{endpoint}}/sr/biz-field-type

{
    "name": "PasswordEncrypted",
    "description": "Encrypted password field",
    "collectionType" : "NONE",
    "basicFieldType": "string",
    "minimum": 255,
    "maximum": 1000
}

###
POST {{endpoint}}/sr/biz-field-type

{
    "name": "ObjectTest2",
    "collectionType" : "NONE",
    "basicFieldType": "object",
    "objectBizFieldTypeRefDTOList": [{
        "bizFieldDomainId": 1,
        "sortOrder": 1
    }]
}