POST {{endpoint}}/sr/biz-field-type

{
    "name": "password",
    "collectionType" : "NONE",
    "basicFieldType": "object",
    "objectBizFieldTypeRefDTOList": [{
        "bizFieldTypeId": 1,
        "refId": 2,
        "parentId": 0,
        "sortOrder": 1
    }],
    "bcTest": "hello"
}